myblog/blog/urls.py
#-*-coding:utf-8_*_
#作者      :71460
#创建时间  :2019/3/15 15:18
#文件      :urls.py.py
#IDE       :PyCharm

from django.urls import path,include
from . import views
app_name = 'blog'
urlpatterns = [
    path('index/', views.index),
    path('article_page/<int:article_id>/', views.article_page ,name='article_page'),
    path('edit/<int:article_id>/', views.edit_page,name='edit_page'),
    path('edit_action/', views.edit_action,name='edit_action'),
]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls',namespace='blog',)),
]

myblog/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32,default='Title')
    content = models.TextField(null=True)
    def __str__(self):
        return self.title

myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
from . import models
def index(request):
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})
#
def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})
def edit_page(request,article_id):
    if str(article_id)=='0':
        return  render(request,'blog/edit_page.html')
    article = models.Article.objects.get(pk = article_id)
    return render(request,'blog/edit_page.html',{'article':article})
def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    article_id = request.POST.get('article_id','0')
    if article_id == '0':
        models.Article.objects.create(title=title, content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})
    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request, 'blog/article_page.html', {'article': article})

myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article Page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br>
<h3>{{ article.content }}</h3>
<br>
<a href="/blog/edit/{{article.id}}">修改文章</a>
</body>
</html>

myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit_Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}
        <input type="hidden" name="article_id" value="{{ article.id | default:'0' }}">
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}">
        </label>
        <br>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}">
        </label>
        <br>
    <input type="submit" value="提交">
</form>
</body>
</html>

myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="/blog/edit/0">新文章</a>
</h1>
{% for article in articles  %}
    <a href="/blog/article_page/{{ article.id }}">{{ article.title }}</a>
    <br/>
{% endfor %}

</body>
</html>


</body>
</html>